import type { Metadata } from "next";
import { Bruno_Ace_SC } from "next/font/google";
import "./globals.css";

const inter = Bruno_Ace_SC({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Utopiara Marketplace",
  description: "Generated by create next app",
  icons: "/logo.ico",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
